routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\GttController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TrafoController;
// use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes([
    'register'=>false
]);

Route::middleware('auth')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('users', UserController::class)->except(['show']);
    Route::resource('gtts', GttController::class)->except(['show']);
    Route::resource('address', AddressController::class)->except(['show']);
    Route::resource('gardu', TrafoController::class)->except(['edit', 'show']);
    Route::get('gardu/create/{gardu?}', [TrafoController::class, 'create'])->name('gardu.create');
    Route::get('gardu/detail/{id}', [TrafoController::class, 'detail'])->name('gardu.detail');
});

resources/views/gardu/detail.blade.php
@extends('layouts.app', [
    'title'         => 'Gardu '.$gardu->code.'-'.$gardu->address,
    'parent'        => 'Gardu',
    'parent_link'   => 'gardu.index',
    'child'         => 'Gardu '.$gardu->code.'-'.$gardu->address
])

@section('content')
@if (session('status'))
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ session('status') }}.</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

<div class="row">
    <div class="col">
        <div class="card card-primary card-outline">
            <div class="card-header">
                {{-- @can('isAdmin') --}}
                <div class="card-tools">
                    <a href="{{route('gardu.create', 1)}}" class="btn btn-sm btn-outline-success"><i class="fa fa-plus"></i> Tambah</a>
                </div>
                {{-- @endcan --}}
                <h5 class="card-title">
                    Data Gardu {{$gardu->code.'-'.$gardu->address}}
                </h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped" id="data" style="width:100%">
                        <thead class="bg-light">
                            <tr>
                                <th scope="col" class="text-center" rowspan="3">#</th>
                                <th scope="col" class="text-center" rowspan="3">Tgl Update</th>
                                <th scope="col" class="text-center" rowspan="3" class="bg-secondary">No GTT</th>
                                <th scope="col" class="text-center" rowspan="3">Alamat</th>
                                <th scope="col" class="text-center" colspan="20">Arus RMS (A)</th>
                                <th scope="col" class="text-center" rowspan="2" colspan="3" class="bg-info">Tegangan</th>
                                <th scope="col" class="text-center" colspan="2">Analisa Beban</th>
                                <th scope="col" class="text-center" rowspan="3">Dokumentasi</th>
                                <th scope="col" class="text-center" rowspan="3" >Aksi</th>      
                            <tr>
                                <th scope="col" class="text-center" colspan="4">LINE A</th>
                                <th scope="col" class="text-center" colspan="4">LINE B</th>
                                <th scope="col" class="text-center" colspan="4">LINE C</th>
                                <th scope="col" class="text-center" colspan="4">LINE D</th>
                                <th scope="col" class="text-center" colspan="4">UTAMA</th>
                                <th scope="col" class="text-center" rowspan="2">DELTA ARUS PHASA RMS MAX-MIN</th>
                                <th scope="col" class="text-center" rowspan="2">ARUS NETRAL DIBANDING <br>
                                 ARUS PHASE TERENDAH</th>
                    
                            </tr>
                            <tr>
                                <td class="bg-danger">R</td>
                                <td class="bg-warning">S</td>
                                <td class="bg-info">T</td>
                                <td class="bg-secondary">N</td>
                                <td class="bg-danger">R</td>
                                <td class="bg-warning">S</td>
                                <td class="bg-info">T</td>
                                <td class="bg-secondary">N</td>
                                <td class="bg-danger">R</td>
                                <td class="bg-warning">S</td>
                                <td class="bg-info">T</td>
                                <td class="bg-secondary">N</td>
                                <td class="bg-danger">R</td>
                                <td class="bg-warning">S</td>
                                <td class="bg-info">T</td>
                                <td class="bg-secondary">N</td>
                                <td class="bg-danger">R</td>
                                <td class="bg-warning">S</td>
                                <td class="bg-info">T</td>
                                <td class="bg-secondary">N</td>
                                <td class="bg-danger">R-N</td>
                                <td class="bg-warning">S-N</td>
                                <td class="bg-info">T-N</td>
                            </tr>                    
                        </thead>
                        <tbody>
                            @foreach ($trafos as $key => $trafo)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $trafo->updated_at->format('d-m-Y H:i:s') }}</td>
                                    <td>{{$trafo->address->code}}</td>
                                    <td>{{$trafo->address->address}}</td>
                                    <td class="bg-danger">{{$trafo->line_ar == 0 ? '-' : $trafo->line_ar}}</td>
                                    <td class="bg-warning">{{$trafo->line_as == 0 ? '-' : $trafo->line_as}}</td>
                                    <td class="bg-info">{{$trafo->line_at == 0 ? '-' : $trafo->line_at}}</td>
                                    <td class="bg-secondary">{{$trafo->line_an == 0 ? '-' : $trafo->line_an}}</td>
                                    <td class="bg-danger">{{$trafo->line_br == 0 ? '-' : $trafo->line_br}}</td>
                                    <td class="bg-warning">{{$trafo->line_bs == 0 ? '-' : $trafo->line_bs}}</td>
                                    <td class="bg-info">{{$trafo->line_bt == 0 ? '-' : $trafo->line_bt}}</td>
                                    <td class="bg-secondary">{{$trafo->line_bn == 0 ? '-' : $trafo->line_bn}}</td>
                                    <td class="bg-danger">{{$trafo->line_cr == 0 ? '-' : $trafo->line_cr}}</td>
                                    <td class="bg-warning">{{$trafo->line_cs == 0 ? '-' : $trafo->line_cs}}</td>
                                    <td class="bg-info">{{$trafo->line_ct == 0 ? '-' : $trafo->line_ct}}</td>
                                    <td class="bg-secondary">{{$trafo->line_cn == 0 ? '-' : $trafo->line_cn}}</td>
                                    <td class="bg-danger">{{$trafo->line_dr == 0 ? '-' : $trafo->line_dr}}</td>
                                    <td class="bg-warning">{{$trafo->line_ds == 0 ? '-' : $trafo->line_ds}}</td>
                                    <td class="bg-info">{{$trafo->line_dt == 0 ? '-' : $trafo->line_dt}}</td>
                                    <td class="bg-secondary">{{$trafo->line_dn == 0 ? '-' : $trafo->line_dn}}</td>
                                    <td class="bg-danger">{{$trafo->line_ur == 0 ? '-' : $trafo->line_ur}}</td>
                                    <td class="bg-warning">{{$trafo->line_us == 0 ? '-' : $trafo->line_us}}</td>
                                    <td class="bg-info">{{$trafo->line_ut == 0 ? '-' : $trafo->line_ut}}</td>
                                    <td class="bg-secondary">{{$trafo->line_un == 0 ? '-' : $trafo->line_un}}</td>
                                    <td class="bg-danger">{{$trafo->tegangan_rn == 0 ? '-' : $trafo->tegangan_rn}}</td>
                                    <td class="bg-warning">{{$trafo->tegangan_sn == 0 ? '-' : $trafo->tegangan_sn}}</td>
                                    <td class="bg-info">{{$trafo->tegangan_tn == 0 ? '-' : $trafo->tegangan_tn}}</td>
                                    <td>{{$trafo->delta}}</td>
                                    <td class="@if($trafo->arus == 'ARUS NETRAL LEBIH BESAR') bg-danger @endif">{{$trafo->arus}}</td>
                                    <td>
                                        @if ($trafo->document != null)
                                            <a href="{{asset('storage/documents/'.$trafo->document)}}" target="_blank" rel="noopener noreferrer">Document ({{$trafo->document}})</a>
                                        @endif
                                    </td>
                                    <td>
                                        {{-- <a href="{{route('gardu.edit', $trafo->id)}}" class="btn btn-sm btn-outline-warning">
                                            <i class="fa fa-edit"></i>
                                        </a> --}}
                                        @can('isAdmin')
                                        @if($latest == $trafo->id)
                                        <button data-bs-toggle="modal" data-bs-target="#delete" onclick="confirmdelete('{{$trafo->id}}','{{$trafo->address->address}}')" class="btn btn-sm btn-outline-danger">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        @endif
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{{-- Modal Delete --}}
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">
                        Hapus <span class="name"></span>
                    </h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id">
                    <p>
                        Hapus <span class="text-success name"></span> ?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"> <i class="fa fa-times"></i> Batal</button>
                    <button type="submit" class="btn btn-outline-danger"> <i class="fa fa-trash"></i> Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('script')
<script>
    setTimeout(function () {
        $(document).ready(function(){
            $('#data').dataTable({
                "ordering": false,
                // "order": [[ 1, 'desc' ]]
            });
        });
    }, 1000);

    function confirmdelete(id,name){
        $('#delete form').attr('action', '/gardu/'+id)
        $('#delete .name').html(name)
        $('#delete input[name=id]').val(id)
    }
</script>
@endsection

resources/views/gardu/edit.blade.php
@extends('layouts.app', [
    'title'         => 'Edit Data Gardu',
    'parent'        => 'Gardu',
    'parent_link'   => 'gardu.index',
    'child'         => 'Edit Data Gardu'
])

@section('content')
    <div class="row">
        <div class="col">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <div class="card-tools">
                        <a href="{{route('gardu.index')}}" class="btn btn-sm btn-outline-secondary"><i class="fa fa-arrow-left"></i> Kembali</a>
                    </div>
                    <h5 class="card-title">Edit Data Gardu</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('gardu.update', $trafo->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row mb-3">
                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Alamat <span class="text-danger">*</span></label>
                                    <select name="address" id="address" class="form-select @error('address') is-invalid @enderror" disabled>
                                        <option value="">Alamat</option>
                                        @foreach ($addresses as $address)
                                            <option value="{{$address->id}}" @if(old('address', $trafo->address_id) == $address->id) selected @endif>{{$address->code.' - '.$address->address}}</option>
                                        @endforeach
                                    </select>
                                    @error('address')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Line A <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">R</span>
                                        <input type="number" class="form-control @error('line_ar') is-invalid @enderror" name="line_ar" placeholder="R" aria-label="R" value="{{old('line_ar', $trafo->line_ar)}}">
                                        <span class="input-group-text">S</span>
                                        <input type="number" class="form-control @error('line_as') is-invalid @enderror" name="line_as" placeholder="S" aria-label="S" value="{{old('line_as', $trafo->line_as)}}">
                                        <span class="input-group-text">T</span>
                                        <input type="number" class="form-control @error('line_at') is-invalid @enderror" name="line_at" placeholder="T" aria-label="T" value="{{old('line_at', $trafo->line_at)}}">
                                        <span class="input-group-text">N</span>
                                        <input type="number" class="form-control @error('line_an') is-invalid @enderror" name="line_an" placeholder="N" aria-label="N" value="{{old('line_an', $trafo->line_an)}}">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Line B <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">R</span>
                                        <input type="number" class="form-control @error('line_br') is-invalid @enderror" name="line_br" placeholder="R" aria-label="R" value="{{old('line_br', $trafo->line_br)}}">
                                        <span class="input-group-text">S</span>
                                        <input type="number" class="form-control @error('line_bs') is-invalid @enderror" name="line_bs" placeholder="S" aria-label="S" value="{{old('line_bs', $trafo->line_bs)}}">
                                        <span class="input-group-text">T</span>
                                        <input type="number" class="form-control @error('line_bt') is-invalid @enderror" name="line_bt" placeholder="T" aria-label="T" value="{{old('line_bt', $trafo->line_bt)}}">
                                        <span class="input-group-text">N</span>
                                        <input type="number" class="form-control @error('line_bn') is-invalid @enderror" name="line_bn" placeholder="N" aria-label="N" value="{{old('line_bn', $trafo->line_bn)}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Line C <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">R</span>
                                        <input type="number" class="form-control @error('line_cr') is-invalid @enderror" name="line_cr" placeholder="R" aria-label="R" value="{{old('line_cr', $trafo->line_cr)}}">
                                        <span class="input-group-text">S</span>
                                        <input type="number" class="form-control @error('line_cs') is-invalid @enderror" name="line_cs" placeholder="S" aria-label="S" value="{{old('line_cs', $trafo->line_cs)}}">
                                        <span class="input-group-text">T</span>
                                        <input type="number" class="form-control @error('line_ct') is-invalid @enderror" name="line_ct" placeholder="T" aria-label="T" value="{{old('line_ct', $trafo->line_ct)}}">
                                        <span class="input-group-text">N</span>
                                        <input type="number" class="form-control @error('line_cn') is-invalid @enderror" name="line_cn" placeholder="N" aria-label="N" value="{{old('line_cn', $trafo->line_cn)}}">
                                      </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Line D <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">R</span>
                                        <input type="number" class="form-control @error('line_dr') is-invalid @enderror" name="line_dr" placeholder="R" aria-label="R" value="{{old('line_dr', $trafo->line_dr)}}">
                                        <span class="input-group-text">S</span>
                                        <input type="number" class="form-control @error('line_ds') is-invalid @enderror" name="line_ds" placeholder="S" aria-label="S" value="{{old('line_ds', $trafo->line_ds)}}">
                                        <span class="input-group-text">T</span>
                                        <input type="number" class="form-control @error('line_dt') is-invalid @enderror" name="line_dt" placeholder="T" aria-label="T" value="{{old('line_dt', $trafo->line_dt)}}">
                                        <span class="input-group-text">N</span>
                                        <input type="number" class="form-control @error('line_dn') is-invalid @enderror" name="line_dn" placeholder="N" aria-label="N" value="{{old('line_dn', $trafo->line_dn)}}">
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Utama <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">R</span>
                                        <input type="number" class="form-control @error('line_ur') is-invalid @enderror" name="line_ur" placeholder="R" aria-label="R" value="{{old('line_ur', $trafo->line_ur)}}">
                                        <span class="input-group-text">S</span>
                                        <input type="number" class="form-control @error('line_us') is-invalid @enderror" name="line_us" placeholder="S" aria-label="S" value="{{old('line_us', $trafo->line_us)}}">
                                        <span class="input-group-text">T</span>
                                        <input type="number" class="form-control @error('line_ut') is-invalid @enderror" name="line_ut" placeholder="T" aria-label="T" value="{{old('line_ut', $trafo->line_ut)}}">
                                        <span class="input-group-text">N</span>
                                        <input type="number" class="form-control @error('line_un') is-invalid @enderror" name="line_un" placeholder="N" aria-label="N" value="{{old('line_un', $trafo->line_un)}}">
                                      </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Tegangan <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">R-N</span>
                                        <input type="number" class="form-control @error('tegangan_rn') is-invalid @enderror" name="tegangan_rn" placeholder="R-N" aria-label="R-N" value="{{old('tegangan_rn', $trafo->tegangan_rn)}}">
                                        <span class="input-group-text">S-N</span>
                                        <input type="number" class="form-control @error('tegangan_sn') is-invalid @enderror" name="tegangan_sn" placeholder="S-N" aria-label="S-N" value="{{old('tegangan_sn', $trafo->tegangan_sn)}}">
                                        <span class="input-group-text">T-N</span>
                                        <input type="number" class="form-control @error('tegangan_tn') is-invalid @enderror" name="tegangan_tn" placeholder="T-N" aria-label="T-N" value="{{old('tegangan_tn', $trafo->tegangan_tn)}}">
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-sm-12">
                                <div class="form group">
                                    <label>Document </label>
                                    {{-- <input type="file" name="document" id="document" class="form-control" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel, application/pdf"> --}}
                                    <input type="file" name="document" id="document" class="form-control" accept="image/*">
                                </div>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Simpan</button>
                                <a href="{{route('gardu.index')}}" class="btn btn-outline-secondary"><i class="fa fa-times"></i> Batal</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

{{-- @section('script')
    <script>
        setTimeout(function () {
        $(document).ready(function(){
            $('#address').select2({
                theme: "classic"
            });
        });
    }, 1000);
    </script>
@endsection --}}