routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\GttController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TrafoController;
// use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes([
    'register'=>false
]);

Route::middleware('auth')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('users', UserController::class)->except(['show']);
    Route::resource('gtts', GttController::class)->except(['show']);
    Route::resource('address', AddressController::class)->except(['show']);
    Route::resource('gardu', TrafoController::class)->except(['edit', 'show']);
    Route::get('gardu/create/{gardu?}', [TrafoController::class, 'create'])->name('gardu.create');
    Route::get('gardu/detail/{id}', [TrafoController::class, 'detail'])->name('gardu.detail');
});

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use App\Models\Address;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['addresses'] = Address::latest()->get();

        return view('address.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('isAdmin');

        return view('address.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('isAdmin');

        $this->validate($request, [
            'code'      => 'required',
            'address'   => 'required'
        ]);

        Address::create([
            'code'    => $request->code,
            'address'   => $request->address
        ]);

        return redirect()->route('address.index')->withStatus('Alamat baru berhasil ditmbahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('isAdmin');

        $address = Address::where('id', $id)->first();

        return view('address.edit', compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('isAdmin');

        $this->validate($request, [
            'code'      => 'required',
            'address'   => 'required'
        ]);

        Address::where('id', $id)->update([
            'code'      => $request->code,
            'address'   => $request->address
        ]);

        return redirect()->route('address.index')->withStatus('Alamat berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('isAdmin');

        Address::where('id', $id)->delete();

        return redirect()->route('address.index')->withStatus('Alamat berhasil dihapus.');
    }
}

resources/views/address/create.blade.php
@extends('layouts.app', [
    'title'         => 'Tambah Alamat',
    'parent'        => 'Alamat',
    'parent_link'   => 'address.index',
    'child'         => 'Tambah Alamat'
])

@section('content')
<div class="row">
    <div class="col">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <div class="card-tools">
                    <a href="{{route('address.index')}}" class="btn btn-sm btn-outline-secondary"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <h5 class="card-title">Tambah Alamat Baru</h5>
            </div>
            <div class="card-body">
                <form action="{{route('address.store')}}" method="post">
                    @csrf
                    
                    <div class="row mb-3">
                        <div class="col-md-6 col-sm-12">
                            <div class="form group">
                                <label>Kode GTT <span class="text-danger">*</span></label>
                                <input type="text" class="form-control @error('code') is-invalid @enderror" name="code" placeholder="Kode GTT" value="{{old('code')}}">
                                @error('code')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form group">
                                <label>Alamat <span class="text-danger">*</span></label>
                                <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" placeholder="Alamat" value="{{old('address')}}">
                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <hr>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Simpan</button>
                            <a href="{{route('address.index')}}" class="btn btn-outline-secondary"><i class="fa fa-times"></i> Batal</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script>
        setTimeout(function () {
        $(document).ready(function(){
            $('#gtt_code').select2({
                theme: "classic"
            });
        });
    }, 1000);
    </script>
@endsection

resources/views/address/edit.blade.php
@extends('layouts.app', [
    'title'         => 'Tambah Alamat',
    'parent'        => 'Alamat',
    'parent_link'   => 'address.index',
    'child'         => 'Tambah Alamat'
])

@section('content')
<div class="row">
    <div class="col">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <div class="card-tools">
                    <a href="{{route('address.index')}}" class="btn btn-sm btn-outline-secondary"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <h5 class="card-title">Tambah Alamat Baru</h5>
            </div>
            <div class="card-body">
                <form action="{{route('address.update', $address->id)}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3">
                        <div class="col-md-6 col-sm-12">
                            <div class="form group">
                                <label>Kode GTT <span class="text-danger">*</span></label>
                                <input type="text" class="form-control @error('code') is-invalid @enderror" name="code" placeholder="Kode GTT" value="{{old('code', $address->code)}}">
                                @error('code')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form group">
                                <label>Alamat <span class="text-danger">*</span></label>
                                <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" placeholder="Alamat" value="{{old('address', $address->address)}}">
                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <hr>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Simpan</button>
                            <a href="{{route('address.index')}}" class="btn btn-outline-secondary"><i class="fa fa-times"></i> Batal</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script>
        setTimeout(function () {
        $(document).ready(function(){
            $('#gtt_code').select2({
                theme: "classic"
            });
        });
    }, 1000);
    </script>
@endsection

resources/views/address/index.blade.php
@extends('layouts.app', [
    'title'         => 'Alamat',
    'parent'        => '',
    'parent_link'   => '',
    'child'         => 'Alamat'
])

@section('content')
@if (session('status'))
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ session('status') }}.</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

<div class="row">
    <div class="col">
        <div class="card card-primary card-outline">
            <div class="card-header">
                @can('isAdmin')
                <div class="card-tools">
                    <a href="{{route('address.create')}}" class="btn btn-sm btn-outline-success"><i class="fa fa-plus"></i> Tambah</a>
                </div>
                @endcan
                <h5 class="card-title">
                    Data Alamat
                </h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="data" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Kode GTT</th>
                                <th>Alamat</th>
                                @can('isAdmin')
                                <th>Aksi</th>
                                @endcan
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($addresses as $key => $address)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $address->code }}</td>
                                    <td>{{ $address->address }}</td>
                                    @can('isAdmin')
                                    <td>
                                        <a href="{{route('address.edit', $address->id)}}" class="btn btn-sm btn-outline-warning">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <button data-bs-toggle="modal" data-bs-target="#delete" onclick="confirmdelete('{{$address->id}}','{{$address->address}}')" class="btn btn-sm btn-outline-danger">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                    @endcan
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{{-- Modal Delete --}}
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">
                        Hapus <span class="name"></span>
                    </h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id">
                    <p>
                        Hapus <span class="text-success name"></span> ?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"> <i class="fa fa-times"></i> Batal</button>
                    <button type="submit" class="btn btn-outline-danger"> <i class="fa fa-trash"></i> Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('script')
<script>
    setTimeout(function () {
        $(document).ready(function(){
            $('#data').dataTable({
                // "ordering": false,
                // "order": [[ 1, 'desc' ]]
            });
        });
    }, 1000);

    function confirmdelete(id,name){
        $('#delete form').attr('action', '/address/'+id)
        $('#delete .name').html(name)
        $('#delete input[name=id]').val(id)
    }
</script>
@endsection